#!/bin/bash

# Configuration parameters
THIS=$(readlink -f .)
ROOT="$HOME"/FMS
SUBFOLDERS=( Agenda Pictures Backups )
COMPILER=gcc
ODIR=obj
SRC=src

# create directories
echo generating directory tree
for folder in ${SUBFOLDERS[@]}
do
  echo '|-'$ROOT/$folder
  mkdir -p $ROOT/$folder
done

# Check if directory exists
echo $THIS/$ODIR
if [ -d $THIS/$ODIR ]
then
    echo "obj directory - OK"
else
    echo "obj directory - Fail... running mkdir."
    mkdir -p $THIS/$ODIR
fi

echo "Compiling source code"
find $SRC -type f -name "*.c" | while read code; do
  echo $code
  $($COMPILER $code -o $ODIR/teste)
done
